environment:
  nodejs_version: "6"
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_GIT_BRANCH: ${APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH}
  GIT_BRANCH: ${APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH}
  GIT_COMMIT_SHA: $(APPVEYOR_REPO_COMMIT)
  COVERALLS_REPO_TOKEN:
    secure: Gq6f8BxVwEemfL6miWIns4T24eQ1t77AApss4cYkZf4k4Kn/fEOtd9F0CVjjB+tj
  CC_TEST_REPORTER_ID:
    secure: hupCEUQXKNBOyVkIY15JakwRRcV3SoT8zEIGwQeMSA6gE86oYyuFgUJ6uzicxfpFwHSio7cWX/gt2z3vOxkynFmct8HKcV46E8GmxC4sdDo=
  HEROKU_API_KEY:
    secure: jPWq020PLzj6m4aJkjSCJcXuwD/CYjSLNs1tPNPBRP8Hs5YvF0cGJCZR+X/BiSJL
  HEROKU_APP_NAME: peaceful-river-48954

  matrix:
    - job_name: Api Tests
      job_group: Tests
    - job_name: Client Tests
      job_group: Tests
    - job_name: Deploy
      # job_depends_on: Tests

image: macOS

for:
  -
    matrix:
      only:
        - job_name: Api Tests
    install:
      - cd api && npm install
    before_test:
      - pwd
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
      - pwd && chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build -d
    test_script:
      - echo reporter id $CC_TEST_REPORTER_ID
      - echo dir ${APPVEYOR_BUILD_FOLDER}
      - npm run test:cov
      # - npm run test:integration
    after_test:
      - git status
      - pwd && ls
      - ./cc-test-reporter after-build -d --id $CC_TEST_REPORTER_ID
      - ls && cd coverage && ls
    build: off

  -
    matrix:
      only:
        - job_name: Client Tests
    install:
      - cd client && npm install
    test_script:
      - npm run test:cov
    after_test:
      - npm run upload:cov || true
      - git status
    build: off
  
  -
    matrix:
      only:
        - job_name: Deploy
    install:
      - npm run install && cd client && npm install
      - ps: curl https://cli-assets.heroku.com/install.sh | sh
      - ps: heroku --version
    build_script:
      - ps: echo Build New tag $env:APPVEYOR_REPO_TAG_NAME
      - npm run build
    after_build:
      - ps: cd api && git init && git add . && git commit -m'Deploy $env:APPVEYOR_REPO_TAG_NAME'
      - ps: git push -f https://heroku:$env:HEROKU_API_KEY@git.heroku.com/$env:HEROKU_APP_NAME.git
    skip_non_tags: true

skip_branch_with_pr: true
