environment:
  nodejs_version: "6"
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_GIT_BRANCH: APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH
  GIT_BRANCH: APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH
  GIT_COMMIT_SHA: APPVEYOR_REPO_COMMIT

  matrix:
    - job_name: Tests Prepare
    - job_name: Api Tests
      job_group: Tests
      job_depends_on: Tests Prepare
    - job_name: Client Tests
      job_group: Tests
      job_depends_on: Tests Prepare
    - job_name: Deploy
      job_depends_on: Tests

for:
  -
    matrix:
      only:
        - job_name: Tests Prepare
    before_test:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ps: ./cc-test-reporter before-build
    build: off
    branches:
      only:
        - master

  -
    matrix:
      only:
        - job_group: Tests
    build: off
    branches:
      only:
        - master

  -
    matrix:
      only:
        - job_name: Api Tests
    install:
      - cd api && npm install
    test_script:
      - pwd
      - npm run test:cov
      - npm run test:integration
    after_test:
      - ps: cd .. && ./cc-test-reporter after-build --prefix /api

  -
    matrix:
      only:
        - job_name: Client Tests
    install:
      - cd client && npm install
    test_script:
      - npm run test:cov
    after_test:
      - npm run upload:cov
      - echo branch %COVERALLS_GIT_BRANCH%
      - cd .. && git status
  
  -
    matrix:
      only:
        - job_name: Deploy
    install:
      - npm run install && cd client && npm install
    build_script:
      - echo Build New tag
    skip_non_tags: true
