environment:
  NODE_VERSION: "14.17"
  GIT_BRANCH: ${APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH}
  GIT_COMMIT_SHA: $(APPVEYOR_REPO_COMMIT)
  CC_TEST_REPORTER_ID: 6236cfcb1fda6970790e1494d8f2425235296d0a63bd449eaed95a18c6cb2257
  CC_TEST_REPORTER: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  HEROKU_APP_NAME: peaceful-river-48954
  HEROKU_API_KEY:
    secure: jPWq020PLzj6m4aJkjSCJcXuwD/CYjSLNs1tPNPBRP8Hs5YvF0cGJCZR+X/BiSJL
  REACT_APP_API_URL: /
  REACT_APP_SOCKET_URL: wss://${HEROKU_APP_NAME}.herokuapp.com/events

  matrix:
    - job_name: Api Tests
      job_group: Tests
    - job_name: Client Tests
      job_group: Tests
    - job_name: Deploy
      job_depends_on: Tests

image: Ubuntu2004
skip_branch_with_pr: true

for:
  -
    matrix:
      only:
        - job_name: Api Tests
    cache:
      - api/node_modules -> api/package-lock.json
    install:
      - nvm use ${NODE_VERSION}
      - cd api && npm install
    before_test:
      - curl -L ${CC_TEST_REPORTER} > ./cc-test-reporter || true
      - chmod +x ./cc-test-reporter || true
      - ./cc-test-reporter before-build || true
    test_script:
      - npm run test:cov
      - npm run test:integration
    after_test:
      - ./cc-test-reporter after-build || true
      - git status
    build: off

  -
    matrix:
      only:
        - job_name: Client Tests
    install:
      - nvm use ${NODE_VERSION}
      - node --version
      - cd client && npm install
    test_script:
      - npm run test:cov
    after_test:
      - echo service $COVERALLS_SERVICE_NAME
      - echo branch $(APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH)
      - echo commit ${APPVEYOR_REPO_COMMIT}
      - echo build branch ${APPVEYOR_REPO_BRANCH}
      - echo pull request ${APPVEYOR_PULL_REQUEST_NUMBER}
      - echo build id ${APPVEYOR_BUILD_ID}
      - echo build number ${APPVEYOR_BUILD_NUMBER}
      - echo build version ${APPVEYOR_BUILD_VERSION}
      - echo pull commit id ${APPVEYOR_PULL_REQUEST_HEAD_COMMIT}
      - echo job id ${APPVEYOR_JOB_ID}
      - COVERALLS_GIT_BRANCH=${APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH} COVERALLS_GIT_COMMIT=${APPVEYOR_REPO_COMMIT} CI_PULL_REQUEST=${APPVEYOR_PULL_REQUEST_NUMBER} npm run upload:cov || true
      - git status && git diff
    build: off
  
  -
    matrix:
      only:
        - job_name: Deploy
    install:
      - nvm use ${NODE_VERSION}
      - npm install && cd client && npm install
      - curl https://cli-assets.heroku.com/install.sh | sh
      - heroku --version
    build_script:
      - npm run typecheck && cd ..
      - npm run build
    after_build:
      - cd api && git init && git config user.email "${GIT_USER_EMAIL}" && git config user.name "${GIT_USER_NAME}"
      - git add . && git commit -m "Deploy ${APPVEYOR_REPO_TAG_NAME}"
      - git push -f https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
    skip_non_tags: true
