version: "3.7"

services:
  postgres:
    # container_name: postgres
    image: postgres
    env_file:
      - docker.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  # api:
  #   container_name: api
  #   build:
  #     context: ./api
  #     target: development
  #   volumes:
  #     - ./api:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "5000:5000"
  #   command: npm run start:dev
  #   depends_on:
  #     - "postgres"

volumes:
  postgres-db: